name: postgres_docker
description: A program that talks to a PostgreSQL database
version: 0.1.0
homepage: https://www.github.com/graphicbeacon/dart_postgres

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  postgres: ^2.1.1

dev_dependencies:
  pedantic: ^1.8.0
